---
title: "Afterword"
author:
  - name: Michael Falk
    email: michael.falk@unimelb.edu.au
    orcid: 0000-0001-9261-8390
    corresponding: true
    url: https://michaelfalk.io
bibliography: references.bib
funding: The project was supported by funding from India's SPARC scheme.
date: 2024-11-06
doi: 10.11647/obp.0423.17
citation:
  type: chapter
  container-title: Digital Humanities in the Indian Rim
  editor: 
    - Hart Cohen
    - Ujjwal Jana
    - Myra Gurney
  publisher: Open Book Publishers
  publisher-place: Cambridge, UK
  isbn: 978-1-80511-387-4
  page: 333-344
  pdf-url: https://books.openbookpublishers.com/10.11647/obp.0423.17.pdf
google-scholar: true
abstract: What justifies the creation of a scholarly community in the "Indian Rim"? In this afterword, I justify the development of a Digital Humanities community in the region, by considering the parallel development of "postcolonial DH" in India and Australia.
toc: true
keywords: Postcolonial Digital Humanities, Digital Humanities in Australia, Digital Humanities in India
license: "CC BY-NC"
---

## Introduction

Why the "Indian Rim"? When we began *DH in the Indian Rim*, we had the utopian desire to construct a new research network in the Global South, to rival the Atlantic network that continues to dominate scholarly life. What could digital humanists in South Asia, Australasia, East Africa and the Persian Gulf teach one another about digital scholarship? How does Digital Humanities (DH) look from the Indian Ocean?

The Indian Ocean does present challenges as a shared space to work. There are few existing institutional links, and what links there are, are typically mediated by Atlantic institutions. This was readily apparent at our first conference, *digital + humanities*, held online in 2019. At that conference, we successfully attracted speakers from South Africa, Nigeria, Abu Dhabi, Mauritius, Australia and India. But our participant from Abu Dhabi worked at a satellite campus of New York University, our Mauritian colleague worked in an academic program certified by a French university, and many of our collaborators from India were either educated or held Faculty positions in Britain or America. I myself convened the conference from my home office in England.

Is it possible—or even desirable—to try and escape the Atlantic? What have we been able to achieve, working within and across the Indian Ocean? Does it even make sense to think of the Indian Ocean as a distinct intellectual *milieu*, when so many scholars from the Ocean have taken up degrees or faculty positions in countries beyond its shores?

Today, India and Australia are well-established players in global DH.[^3] It is no surprise that this book, though it began with broader aspirations, has resolved into a collaboration between scholars from these two nations. As these contributions indicate, scholars in India and Australia are flourishing in the mainstream of DH: they build databases, remediate archives, process cultural data, critique technology, and wonder how to convert DH from a field of research into a viable teaching program under local conditions. In these respects, neither Indian nor Australian DH need to make excuses for themselves.

[^3]: For an overview of Indian DH, readers may consult @risam_south_2020, @dodd_exploring_2020 and @zaidi_literary_2022, as well as the special issue of *Digital Humanities Quarterley* on minimal computing, introduced in @risam_introduction_2022. Unfortunately there are no comparable sources on the development of DH in Australia.

This is all very well, but it is not enough to justify *DH in the Indian Rim*. If scholars around the Indian Ocean Rim wish to form a distinctive group, then their group must have some distinctive qualities. What are they?

As Cohen and Jana suggest in their introduction, the greatest commonality among Indian Rim countries is our shared history of colonisation. To be sure, the history of colonisation is never anywhere the same. Australia is a settler-colonial state with a white majority, hundreds of Indigenous nations and a growing plurality of global migrants—including some 600,000 from India (Chand, this volume). India is a large federation of postcolonial states, with an enormous global diaspora, and its own history of domination by caste, religion, language and region. Despite these differences, the legacy of colonisation has inflected DH in both countries, and suggests that continued regional collaboration could be productive.

In what follows, I discuss three main strands of postcolonial DH, indicating how Indian and Australian digital humanists have made unique and complementary contributions to them. The strands are *counter-archiving*, *multilingual DH* and *jugaad*, or *minimal computing*. Like all strands, these three are intertwined, but I hope to separate them adequately for discussion. I conclude with a reflection on possible futures for DH in the Indian Rim. Indigenous scholars are entering the Australian academy in greater numbers. Indian scholars are reviving Sanskrit learning, and using it to critique dominant Western methodologies with ever greater success. These developments raise the possibility of a fundamentally new kind of DH, with new origin stories and new directions, liberated from the inspiring but also stifling myths that have hitherto given "DHers" their sense of academic identity.[see @jones_roberto_2016]

## Counter-archiving

Cohen presents a splendid example of *counter-archiving* in his chapter on the Strehlow Research Centre (SRC). In this case, the project 'counters' traditional archives by respecting the cultural authority of its subjects. Although much of the research Cohen describes is technologically at the cutting-edge, he asserts quite rightly that the project's real innovation lies "in developing protocols and processes for digitising culturally sensitive films" (this volume). The SRC is a closed, rather than an open archive. It gives Arrernte people control over their cultural heritage. As Cohen's impressive bibliography demonstrates, this closedness of the archive has not prevented research. Articles and monographs continue to flow. It is quite possible that closing the archive may have *opened* Arrernte people to research, by giving them confidence that they can set the terms. Of course the most important aspect of the project is its usefulness to traditional owners, who are drawing on the archive to "revitalise ceremonies that haven't been performed for generations."

The preeminent DH theorist of counter-archiving is Indian-American scholar Roopika Risam. In *New Digital Worlds* (2019), she prpounds a theory of postcolonial "world-making," which can usefully be applied to Cohen's project. As Risam sees it, postcolonial DH is both critical and practical. On the critical side, postcolonial DH "addresses underexplored questions of power, globalization, and colonial and neocolonial ideologies that are shaping the digital cultural record in its mediated, material form[.]" On the practical side, postcolonial DH scholars "[design] new tools, methods, and workflows that are based in local practices [...] to create space for underrepresented communities to populate the digital cultural record with their own stories."[@risam_new_2019, p. 9] Both these sides of postcolonial DH are exemplified in Cohen's project. It began with a critique of the Strehlow Research Centre's settler-colonial heritage, and morphed into a practical project to digitise the archive according to Arrernte cultural protocols.

India's history of colonisation is different to Australia's, and accordingly the critical side of counter-archiving is different. The practical side, however, is often similar. A good example is SPARROW, an oral history database curated for many years by C.S. Lakshmi. Lakshmi set up the archive to combat dominant narratives about the "Third World," which is "supposed to worry about slums, environment, legal aid for women, health care, rural development and so on".[quoted in @dodd_ethics_2020, p. 142] Her archive allows Indian women to eschew these dominant narratives, and to describe their lives in their own way for their own reasons. On the critical side, therefore, this project is quite distinct from Cohen's: Cohen critiques a settler-colonial archive in the possession of a white ruling class, and helps to return the archive to its traditional owners. Lakshmi sets up a new archive to tell stories that are missing from existing archives about the "Third World." On the practical side, however, Lakshmi's project converges with Cohen's:

> What happens is the demand for fully open archiving comes from the West. I’m not for fully-open archiving. I’ll tell you why. For example, let me say I have interviewed an Indian woman worker who tells me all about her life: her personal life, her sexual life, everything. It’s available with the archives. We have also digitized it in a way that people can read it on their computer; it’s possible. I can give excerpts of it, for example, but we can’t make the whole thing available online because I feel that when you put it on the web, millions of people can read it for no purpose.[quoted in @dodd_ethics_2020, p. 143]

Like Cohen, Lakshmi has developed protocols that rub against the dominant digital ideology of "openness" or the "free flow of information."[For a critique of the "openness" ideal, see @tkacz_wikipedia_2015, chap. 1] In this case, Lakshmi has developed protocols informally over many decades with her informants, devising a locally appropriate division between revelation and concealment.[She rejects the public/private distinction: @dodd_ethics_2020, p. 150] Lakshmi is typical. According to Nishant Shah, Indian DH has entered a "post-access" phase.[@shah_digital_2019] Merely opening the world's digital cultural record is no longer the primary aim.

In Australia, counter-archiving is increasingly well organised, overseen by Indigenous scholars and archivists. Tahu Kuktai and John Taylor have edited a seminal collection on *Indigenous Data Sovereignty*, with contributors from Australia, Aoteoroa/New Zealand and North America.[@kukutai_indigenous_2016] Organisations such as the [Indigenous Data Network](https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network) and the [Indigenous Archives Collective](https://indigenousarchives.net/) provide platforms for Indigenous scholars and archivists to critique existing archives and organise to build new ones. The [Australian Research Data Commons](https://ardc.edu.au/) has subsequently adopted the CARE principles as core guidelines, alongside the more familiar FAIR principles.[^1] Major DH archives such as [People Australia](https://peopleaustralia.anu.edu.au/), [Austlit/Blackwords](https://www.austlit.edu.au/), and [Trove](https://trove.nla.gov.au/) have, with varying degrees of success, either brought in Indigenous managers or adopted more culturally sensitive practices.[^2] Indigenous scholars are increasingly prominent in public debates about knowledge institutions. In the last two years, prominent Aboriginal scholars have released highly publicised reports which starkly but constructively criticise Wikipedia, the world's preeminent knowledge institution.[@thorpe_wikimedia_2023; @carlson_i_2024] Although many Australian researchers (the author included) continue to work in traditional digital fields such as text analysis and cultural databasing, where openness and reproducibility are prized, it seems that Australia is entering its own "post-access" phase of DH.

[^1]: @noauthor_care_2022; see Nayak and Rana, this volume, for a definition of the CARE principles

[^2]: See, for example, Trove's documentation on cultural safety for first Australians: @noauthor_cultural_2020.

## Multilingual DH

India and Australia are profoundly multilingual, as are most countries in the Indian Rim. More than 400 languages are spoken in India.[@noauthor_glottoscope_nodate] In Australia, there are more than 200 Indigenous languages, and more than 20% of Australians speak a language other than English at home.[@noauthor_glottoscope_nodate-1; @noauthor_cultural_2022] In this respect, DH in the Indian Rim again contrasts with its Atlantic counterpart. Although of course there are many Indigenous and migrant languages in North America, and several European nations with more than one official language, Atlantic DH has seldom had to grapple with the same degree of multilingualism as DH in the Indian Rim.

In India, multilingualism is essentially compulsory. It is not possible to research digital artefacts or platforms without encountering multiple languages. This is illustrated beautifully in Chand's chapter. Chand is doubly diasporic: a member of Fiji's Indian minority, who subsequently migrated to Australia. Her research into dating apps reveals a network of languages linking members of the Indian diaspora across cities and oceans. Some languages are supported on some platforms, and some on others. She must rely on her own multilingual proficiency in order to examine and understand the platforms. Compulsory multilingualism is also a feature of Nayak and Rana's research. Even though they use an English translation of the text, they must be constantly mindful of the underlying Sanskrit. Sometimes a Sanskrit word surfaces in the English translation (e.g. *stridhana*). At other times, the translation requires careful interpretation (e.g. when the word "class" is used in the meaning of "caste"). English has not been in contact with Sanskrit as long as it has been in contact with Latin or Greek. The Indian scholar writing in English must always be aware of a gap between the text under study and the academic text they are writing. Thus in this case, too, multilingualism is *compulsory*, where in the Atlantic world it is often avoidable.

Indian DH projects are almost inevitably multilingual. The [Bibliography of Modern and Contemporary Art Writing of South Asia](https://aaabibliography.org/) records more than 12,000 pieces of art writing in 12 languages.[@ragavan_processes_2020] The [1947 Partition Archive](https://in.1947partitionarchive.org/) contains more than 10,000 oral histories in 37 languages. [Bichitra](http://bichitra.jdvu.ac.in/), an online variorum of Rabindranath Tagore, contains a mixture of manuscripts in two languages—English and Bengali—which use different scripts. This multilingualism has shaped the project at every level, from the data model of the bibliography, the encoding scheme of the texts, and the algorithm of the collation system.[@bhowmik_bichitra_2022] Even Indian projects that begin monolingual have a tendency to become multilingual. [Rekhta.org](https://rekhta.org/) began as an archive of Urdu poetry, but was extended in 2020 to include Hindi texts.[@zaidi_rekhta_2022, p. 12]

Despite the hegemony of English, DH in Australia has been unusually multilingual for a long time. This is probably due to the relative prominence of documentary linguists, archaeologists and anthropologists in Australian DH. The flagship project for multilingual DH in Australia is [PARADISEC](https://www.paradisec.org.au/), a large digital archive that conserves the cultural and linguistic heritage of the Australia-Pacific. It is a venerable project, more than 20 years old, but still expanding and improving. It contains recordings, videos and written materials in 1370 languages from across Australia and the Pacific. As I discuss in the next section, PARADISEC has taken special measures to make its materials available to the communities it represents, and has control measures in place to allow them to protect their cultural data. Other Australian projects in a similar vein include: [Austlang](https://collection.aiatsis.gov.au/austlang/search), which provides metadata about Indigenous Australian Languages; the [Living Languages Platform](https://www.livinglanguages.org.au/), which provides free dictionary apps of Indigenous Australian languages; and the [AUSLAN Signbank](https://auslan.org.au/), an innovative video dictionary of Australian Sign Language. Digital resources for Australia's many community languages, such as Arabic, Chinese or Bengali, are not so well developed. It is notable, for example, that the [Language Data Commons of Australia](https://www.ldaca.edu.au/) currently includes data on 31 languages, including AUSLAN and numerous Indigenous Languages, but no resources for migrant languages other than English.[@noauthor_ldaca_nodate]

These classic Australian examples of multilingual DH have mostly been aimed at specialist researchers and the communities they study. More recently, innovative DH researchers have found ways to reach a wider audience. As part of the *Waves of Words* project (mentioned in Burrows, this volume), Rachel Hendery and Andrew Burrell developed *Glossopticon*, a virtual reality experience in which users could explore the linguistic diversity of the Pacific with all the senses.[@hendery_playful_2019] Users can fly across the Pacific, following known canoe routes, and hear recorded speech from PARADISEC on the islands. It has hitherto been difficult to incorporate multiple languages in the traditional DH fields of text analysis and cultural analytics. But Indian and Australian DHers are steadily making the effort.

## *Jugaad*; or minimal computing

One of the most important aspects of postcolonial DH is *jugaad*, or minimal computing. Minimal computing is an ambiguous concept in DH, but usually "connotes digital humanities work undertaken in the context of some set of constraints" [@risam_introduction_2022]. Minimal computing has been a key theme in Indian DH, where the constraints are often greater than in Atlantic DH. Indian digital humanists theorise minimal computing under the title *jugaad*, an untranslatable word that intersects with the English "makeshift" or "hack." As Padmini Ray Murray and Chris Hand observe in their canonical treatment of the topic, *jugaad* resembles other practices of "technological disobedience" in the Global South, including "*Gambiarra* in Brazil, *Rebusque* in Colombia, and *Jua Kali* in Kenya."[@ray_murray_making_2015, p. 144]

*Jugaad* is a tricky concept to institutionalise, as Souvik Mukherjee points out.[@mukherjee_digital_2020] If *jugaad* is an inherently disobedient practice, how can it be incorporated into the disciplined structures of an academic degree? Ray Murray herself is more sanguine, observing an interesting fact about DH pedegogy in India: India's first graduate DH degree was not founded in an English or History department, as is usually the case, but was founded in a school of Design.[@ray_murray_decolonising_2020, p. 130] In India, it seems, DH lays a stronger emphasis on *making things work* rather than *analysing the cultural record*.

The same cannot be said for Australia. To my knowledge, only four Australian Universities have offered teaching programs in DH: Monash University, the Australian National University, Western Sydney University and the University of Melbourne. In no case was the program offered as part of a degree in Design. Literature, linguistics, history and information science have been the dominant disciplines, as far as DH pedagogy is concerned.

But there has been a role for minimal computing and critical making in Australian DH. The most poetic example again comes from PARADISEC. PARADISEC itself, like many decades-old Humanities databases, is optimised for use on a desktop connected to broadband internet. Desktops with broadband connections are relatively rare in the steamy villages of Vanuatu or the highlands of Papua New Guinea. Desktops are likewise less common than they ought to be in remote Aboriginal communities in Australia. Accordingly the project has developed technology to enable local communities to access their data offline. Linguistic and cultural data are loaded onto a Raspberry Pi in a static format such as html. The Raspberry Pi then generates a local WiFi network, and community members can access the data using their phones.[@thieberger_technology_2020; @thieberger_doing_2023]

In my own work, coordinating the [Digital Studies](https://study.unimelb.edu.au/find/courses/minor/digital-studies-minor/) program at the University of Melbourne, I have taken inspiration from *jugaad*. To teach my first-year students how to make computers do things, I have them play *Turing Tumble*, an AUD$100 mechanical computer. I have them create games using [bitsy](https://make.bitsy.org), a web-based "8-bit" game development program. I have them submit their assignments in the *PechaKucha* format, a highly constrained kind of slideshow. Of course, at the University of Melbourne, such constraints are artificial. We are a wealthy institution where—despite the usual grumbles—resources are plentiful, and our (mostly) privileged students are (mostly) able to obtain what they need. But the inspiring examples of my Indian colleagues—and other practitioners in the Global South—have demonstrated the value of constraint, if we want our students to make things *critically*.

## Futures past

This volume demonstrates the willingness of Australian and Indian scholars to build a new intellectual community in the Indian Ocean Rim. I believe their is an appetite for broader connections across the Ocean, which would build on more ancient connections. On the western shores of the Ocean, the Swahili have a saying, *rupia kwa ya pili*—"as like as two rupees." Rupees once travelled the length and breadth of the Indian Ocean on traders' *dhows*. In Arnhem Land, in Australia's north, the Yolŋu Matha word for money is *rrupiya*, a word that Yolŋu people presumably learned from Makassan traders who came to their shores to gather trepang.[@noauthor_rrupiya_nodate] The currents of the Indian Ocean have flowed with blood in recent centuries, but also with else besides.

In both India and Australia, new visions for our digital future are stirring, visions that once were repressed. In India, some scholars have drawn on classical Indian scholarship to critique modern methods. Nirmala Menon, for example, has rebuilt postcolonial translation theory with the help of classical Sanskrit concepts: *dhavani*, *bhava*, *shruti* and *rasa*.[@menon_remapping_2016, chap. 4] Menon now oversees many multilingual DH projects in the [Jaya Prakash Narayan National Centre of Excellence in the Humanities](https://jpnnationalcentre.com/). In Australia, Indigenous futurists draw on traditional storytelling to envisage alternative socio-technical systems. In her story "Campfire," for example, Nyungar technologist Kathryn Gledhill-Tucker imagines a distributed system of Internet-of-Things devices, *Campfire*, around which Aboriginal people sit to talk to one another and care for country.[@gledhill-tucker_campfire_2024] The pasts of the Indian Ocean are diverse. So accordingly are its futures.

The people of the Indian Ocean are not *rupia kwa ya pili*, except insofar as any two rupees mark out different paths in the same arena of exchange. The exchange is surely worth it. Digital Humanities may sometimes seem an eccentric affair, the attempts of a few crazed academics to twist the computer into a shape that it is not made to assume. But the work of humanising the computer *is* important, and must be enriched by a new and invigorated DH in the Indian Rim.

## References
